#!/bin/bash

# Get the last commit date
LAST_COMMIT_DATE=$(git log -1 --format="%cd" --date=format:"%B %-d, %Y" 2>/dev/null)

# If git command fails, use current date
if [ -z "$LAST_COMMIT_DATE" ]; then
  LAST_COMMIT_DATE=$(date "+%B %-d, %Y")
fi

# Create _data directory if it doesn't exist
mkdir -p _data

# Write the date to a YAML data file
cat > _data/git.yml << EOF
# Auto-generated by scripts/update-git-date.sh
# This file is updated automatically before each build
last_commit_date: "$LAST_COMMIT_DATE"
EOF

echo "Updated _data/git.yml with last commit date: $LAST_COMMIT_DATE"
